### ISSUE TITLE
Cross-sell tracking for WP Rocket & Imagify to RankMath

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/plugin-family#16]
**Context**
Through the plugin-family, we are offering RankMath with a one-click install to WP Rocket & Imagify. 

**Expected behavior**
We would like to measure how effective this is and get:
- A counter of installs of RankMath from WP Rocket
- A counter of installs of RankMath from Imagify
- A counter of upgrade to RankMath PRO after installing the free version from WP Rocket
- A counter of upgrade to RankMath PRO after installing the free version from Imagify

The approach should be easily expandable to other plugins / cross-selling initiative.

**Additional information**
Detailed Slack discussion about the technical approach: https://group-onecom.slack.com/archives/C082QRGHTJA/p1732825105335409
High-level JIRA task: https://group-one.atlassian.net/browse/STEPUP-534

**GitLab tasks**
- [x] [Redirection for plugin-family RankMath download tracking](https://gitlab.group.one/rankmath/rankmath.com-website/-/issues/5)
- [ ] [Change upgrade link in RankMath if install is coming from plugin-family](https://gitlab.group.one/rankmath/seo-by-rank-math-private/-/issues/3353)
- [ ] [Track conversions to PRO from specific plugins](https://gitlab.group.one/rankmath/rankmath.com-website/-/issues/6)

**Comment by MathieuLamiot** [comment]
Tracking upsell to PRO might be out of scope now. We are investigating other approaches.
